### PR TITLE
Fix ema decay when filtered.

### PR DESCRIPTION
**Pull request by ryan-gunderson**
Replace fill forward with zero.

### CODE REVIEW

**Review by OrestZborowski-SIG — COMMENTED** [review]
Just curious why the huge whitespace changes? Makes for a more complicated diff.

**Comment by ryan-gunderson** [comment]
@OrestZborowski-SIG Not intentional.  I suspect it has something to do with line endings?  I only saw the two lines in my diff.

**Comment by jack-pappas** [comment]
@ryan-gunderson You should be able to rebase your changes on the latest main now and get rid of all of the whitespace changes.

**Comment by staffantj** [comment]
Replaced by #116

**Pull request closed without merging**
